# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta3-demo
  title: Create Azure Virtual Machine
  description: scaffolder v1beta3 template demo
spec:
  owner: ecarlos.a.silva@gmail.com
  type: service

  parameters:
    - title: Virtual Machine Name
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component        
  steps:
    - id: writeFile
      name: Create File
      action: roadiehq:utils:fs:write
      input:
       path: ${{ parameters.path }}
       content: |
                  azurerm_resource_group_name = ${pa}
                  azurerm_key = "snackingnextgen-dev-comp-eastus2.tfstate"
                  azurerm_storage_account_name = "oddatfstateeus2devsa"
                  azurerm_container_name = "resource-tfstate"
                  solution_name       = "snackingnextgen-prod"
                  region              = "eastus"
                  environment         = "prod"
                  vnet_name           = "oddacoreeusprodvnet"
                  vnet_rg             = "ODDACORE-NETWORK-EUS-PROD-RG"
                  resource_group_name = "resource_group_name"
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}